### ISSUE TITLE
Doesn't work without JavaScript

### ISSUE THREAD

**Issue by potatoeggy** [magicalsoup/magicalsoup-website#1]
![image](https://user-images.githubusercontent.com/25178974/171040214-94a0a847-f31d-4ba8-b239-8874ddabf77b.png)

On devices that have limited or no JavaScript support, such as those that disable it for power or security concerns, the website is not usable.

Tested on Chrome 101 and Firefox 100 on Arch Linux.

**Comment by vincentjguo** [comment]
+1

**Comment by jamesxsu** [comment]
It’s built using nextjs and I’m asssuming it needs js support, I’m not sure how to get around this
